### ISSUE TITLE
SubsiteAdminExtension class name collision

### ISSUE THREAD

**Issue by michalkleiner** [adrexia/silverstripe-subsite-modeladmins#5]
Hi @adrexia,

the SubsiteAdminExtension class also exists in https://github.com/lekoala/silverstripe-subsites-extras, making it difficult to use both modules at the same time.

I can submit a PR namespacing all the extension classes if you suggest what namespace you'd like to use.

Cheers
Michal

**Comment by adrexia** [comment]
Sorry for the lack of response, I missed this. I've added namespacing for ss4 support. Feel free to backport to ss3. Its just `Adrexia\SubsiteModelAdmins`

**Comment by adrexia** [comment]
Fixed for ss4
